name: CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "src/**"
      - "test/**"
      - "example/**"
      - "Project.toml"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "example/**"
      - "Project.toml"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - "1.6" # next LTS
          - "1" # latest stable 1.x release of Julia
          - nightly
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
          - x86
        # 32-bit Julia binaries are not available on macOS
        exclude:
          - os: macOS-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v2
        with:
          file: ./lcov.info
